name: Run Visual Basic 6.0 build
description: Run vb.exe make for specified VB project
inputs:
  vbpprojectpath:
    description: path to visual basic project (*.vbp)
    required: true
  outdir:
    description: output path for build output
    required: false
    default: '.'
runs: 
  using: 'composite'
  steps:
    - name: Compile vbp file
      shell: pwsh
      run: |
        $vbpprojectpath = "${{ inputs.vbpprojectpath }}"
        $outputdir = "${{ inputs.outputdir }}"
        Write-Output "Visual Basic project path is $vbpprojectpath"
        Write-Output "Output directory is $outputdir"
        VB6 /MAKE $vbpprojectpath /outdir $outputdir
        echo "::set-output name=buildstatus::$?"
