name: Run Visual Basic 6.0 build
description: Run vb.exe make for specified VB project
inputs:
  vpbpath:
    description: path to visual basic project (*.vbp)
    required: true
  outdir:
    description: output path for build output
    required: false
    default: "."
shell: pwsh
run: |
  $vbprojectpath = "c:\actions-runner\_work\MyVBApp\MyVBApp\DummyApp.vbp"
  $outputdir = "c:\actions-runner\_work\MyVBApp\MyVBApp\"
  echo $vbprojectpath $outputdir
